#!/usr/bin/env bash
# One-command install and feature profiles. Default product paths (init.bash,
# scripts/dev-setup.bash) still never write ~/.bashrc. This script writes
# ~/.config/mbx/config.bash always, and ~/.bashrc only with --bashrc.
set -euo pipefail

ROOT=$(cd -- "${BASH_SOURCE[0]%/*}/.." && pwd -P)
PROFILE=comfort
PROFILE_SET=0
WRITE_BASHRC=0
NO_BUILD=0
DOWNLOAD=0
ACTION=install

usage() {
    cat <<'EOF'
Install MBX and enable a feature profile.

Usage:
  bash scripts/install.bash [--profile comfort|highlight|prompt] [--bashrc] [--no-build]
  bash scripts/install.bash --download [...]   # fetch the prebuilt v0.1.0 release binary instead of building
  bash scripts/install.bash --interactive [--profile NAME] [--bashrc] [--no-build]
  bash scripts/install.bash --status
  bash scripts/install.bash --uninstall-bashrc
  bash scripts/configure.bash          # interactive option menu
  mbx_configure                        # same, after the loader is sourced

Profiles:
  comfort    Highest QoL: history, ghost suggestions, overlay, wrap git
             (highlight is off; it cannot combine with ghost)
  highlight  History, syntax highlighting, overlay, wrap git (no ghost)
  prompt     Prompt only; all opt-in features stay off

--bashrc     Append a managed block to ~/.bashrc (idempotent)
--interactive  Open the option menu (scripts/configure.bash)
--no-build   Skip cargo build (tests / already built)
--download   Fetch the matching prebuilt release binary instead of building
             (Linux x86_64/aarch64 only; falls back to cargo build on failure)

Environment variables already set in your shell always win over the config file.
History stays off until a profile that opts in, or you export MBX_HISTORY=1.
EOF
}

config_path() {
    local base=${XDG_CONFIG_HOME:-}
    if [[ $base != /* ]]; then
        base=${HOME:?HOME is required}/.config
    fi
    printf '%s\n' "$base/mbx/config.bash"
}

write_profile() {
    local path=$1
    local dir=${path%/*}
    mkdir -p "$dir"
    chmod 700 "$dir" 2>/dev/null || true
    case $PROFILE in
        comfort)
            cat >"$path" <<'EOF'
# MBX profile: comfort
# Generated by scripts/install.bash. Edit freely.
# Variables already set in the environment are not overridden.

[[ ${MBX_HISTORY+x} ]] || export MBX_HISTORY=1
[[ ${MBX_GHOST+x} ]] || export MBX_GHOST=1
[[ ${MBX_TUI+x} ]] || export MBX_TUI=1
[[ ${MBX_COMP_OVERLAY+x} ]] || export MBX_COMP_OVERLAY=1
[[ ${MBX_COMP_WRAP+x} ]] || export MBX_COMP_WRAP=git
# Highlight stays off: MBX_HIGHLIGHT=1 cannot combine with ghost.
EOF
            ;;
        highlight)
            cat >"$path" <<'EOF'
# MBX profile: highlight
# Generated by scripts/install.bash. Edit freely.

[[ ${MBX_HISTORY+x} ]] || export MBX_HISTORY=1
[[ ${MBX_HIGHLIGHT+x} ]] || export MBX_HIGHLIGHT=1
[[ ${MBX_COMP_OVERLAY+x} ]] || export MBX_COMP_OVERLAY=1
[[ ${MBX_COMP_WRAP+x} ]] || export MBX_COMP_WRAP=git
# Ghost stays off: MBX_GHOST=1 cannot combine with highlight.
EOF
            ;;
        prompt)
            cat >"$path" <<'EOF'
# MBX profile: prompt
# Generated by scripts/install.bash. Opt-in features stay off.

# export MBX_HISTORY=1
# export MBX_GHOST=1
# export MBX_HIGHLIGHT=1
# export MBX_COMP_OVERLAY=1
# export MBX_COMP_WRAP=git
EOF
            ;;
        *)
            printf 'unknown profile: %s\n' "$PROFILE" >&2
            exit 2
            ;;
    esac
    chmod 600 "$path" 2>/dev/null || true
}

BEGIN_MARK='# >>> mbx begin'
END_MARK='# <<< mbx end'

# Resolve ~/.bashrc for writes. Follow a symlink only when the target is a
# regular file (or not yet created) under $HOME, so dotfile managers keep
# their link. Refuse anything else.
bashrc_write_path() {
    local bashrc=${HOME:?HOME is required}/.bashrc
    local target
    if [[ -L $bashrc ]]; then
        target=$(readlink -f -- "$bashrc" 2>/dev/null) || {
            printf 'mbx install: cannot resolve ~/.bashrc symlink\n' >&2
            return 1
        }
        if [[ -z $target || $target != "$HOME"/* ]]; then
            printf 'mbx install: refusing ~/.bashrc symlink outside HOME\n' >&2
            return 1
        fi
        if [[ -e $target && ! -f $target ]]; then
            printf 'mbx install: ~/.bashrc symlink target is not a regular file\n' >&2
            return 1
        fi
        REPLY=$target
        return 0
    fi
    REPLY=$bashrc
}

strip_managed_block() {
    local src=$1 dest=$2
    local skip=0 line
    : >"$dest"
    [[ -f $src ]] || return 0
    while IFS= read -r line || [[ -n $line ]]; do
        if [[ $line == "$BEGIN_MARK" ]]; then
            skip=1
            continue
        fi
        if [[ $line == "$END_MARK" ]]; then
            skip=0
            continue
        fi
        ((skip == 1)) && continue
        printf '%s\n' "$line" >>"$dest"
    done <"$src"
}

write_bashrc() {
    local dest tmp cleaned
    bashrc_write_path || return 1
    dest=$REPLY
    tmp=$(mktemp)
    cleaned=$(mktemp)
    if [[ -f $dest ]]; then
        strip_managed_block "$dest" "$cleaned"
    else
        : >"$cleaned"
    fi
    {
        cat "$cleaned"
        printf '\n%s\n' "$BEGIN_MARK"
        printf '# Managed by ColorBash scripts/install.bash. Do not edit this block.\n'
        printf 'export MBX_BIN=%q\n' "$ROOT/target/release/mbx"
        printf 'source %q\n' "$ROOT/bash/init.bash"
        printf '%s\n' "$END_MARK"
    } >"$tmp"
    mv "$tmp" "$dest"
    rm -f "$cleaned"
}

uninstall_bashrc() {
    local dest cleaned
    [[ -e ${HOME:?HOME is required}/.bashrc || -L ${HOME}/.bashrc ]] || return 0
    bashrc_write_path || return 1
    dest=$REPLY
    [[ -f $dest ]] || return 0
    cleaned=$(mktemp)
    strip_managed_block "$dest" "$cleaned"
    mv "$cleaned" "$dest"
}

print_status() {
    local path
    path=$(config_path)
    printf 'config: %s\n' "$path"
    if [[ -f $path ]]; then
        cat "$path"
    else
        printf '(missing — opt-in flags stay off)\n'
    fi
    printf '\ninit: source %q\n' "$ROOT/bash/init.bash"
    if [[ -f ${HOME:-}/.bashrc ]] && grep -Fq "$BEGIN_MARK" "$HOME/.bashrc"; then
        printf 'bashrc: managed MBX block present\n'
    else
        printf 'bashrc: no managed MBX block\n'
    fi
}

print_cheatsheet() {
    cat <<EOF

Reload a new shell, then run mbx_help for the full key list.
  quick summary: mbx_status      diagnose: mbx_doctor
  reconfigure: bash $ROOT/scripts/configure.bash
  remove from bashrc: bash $ROOT/scripts/install.bash --uninstall-bashrc
EOF
}


# REL-001: with --download, fetch the prebuilt release binary matching this
# checkout's version and machine instead of compiling. The tarball is
# checksum-verified and only the `mbx` binary is extracted to the same path
# cargo would produce, so everything downstream is unchanged. Any failure
# falls back to the cargo build path.
download_release_binary() {
    local version target url tmp
    version=$(sed -n 's/^version = "\(.*\)"/\1/p' "$ROOT/crates/cli/Cargo.toml" | head -1)
    [[ -n $version ]] || return 1
    case $(uname -s)-$(uname -m) in
        Linux-x86_64) target=x86_64-unknown-linux-gnu ;;
        Linux-aarch64) target=aarch64-unknown-linux-gnu ;;
        *) return 1 ;;
    esac
    url="https://github.com/ishitvagoel/ColorBash/releases/download/v${version}/mbx-${version}-${target}.tar.gz"
    tmp=$(mktemp -d)
    printf 'Downloading %s\n' "$url"
    curl -fsSL -o "$tmp/mbx-${version}-${target}.tar.gz" "$url" || {
        printf 'Download failed; falling back to cargo build.\n' >&2
        return 1
    }
    (cd "$tmp" && curl -fsSLO "$url.sha256" && sha256sum -c "mbx-${version}-${target}.tar.gz.sha256" >/dev/null) || {
        printf 'Checksum mismatch; falling back to cargo build.\n' >&2
        return 1
    }
    tar xzf "$tmp/mbx-${version}-${target}.tar.gz" -C "$tmp"
    mkdir -p "$ROOT/target/release"
    cp "$tmp/mbx-${version}-${target}/mbx" "$ROOT/target/release/mbx" || {
        printf 'Extraction failed; falling back to cargo build.\n' >&2
        return 1
    }
    rm -rf "$tmp"
    printf 'Installed prebuilt helper: %s\n' "$ROOT/target/release/mbx"
}

install_build_or_download() {
    if ((DOWNLOAD == 1)); then
        if command -v curl >/dev/null 2>&1 && download_release_binary; then
            return 0
        fi
        if ((NO_BUILD == 1)); then
            printf 'mbx install: --download failed and --no-build forbids building.\n' >&2
            exit 2
        fi
        printf 'Falling back to cargo build.\n' >&2
    fi
    command -v cargo >/dev/null 2>&1 || {
        printf 'mbx install: Rust/Cargo is required (https://rustup.rs).\n' >&2
        exit 2
    }
    (
        cd "$ROOT"
        cargo build --release --workspace
    )
}

while (($#)); do
    case $1 in
        -h | --help)
            usage
            exit 0
            ;;
        --profile)
            PROFILE=${2:?--profile needs comfort, highlight, or prompt}
            PROFILE_SET=1
            shift 2
            ;;
        --bashrc)
            WRITE_BASHRC=1
            shift
            ;;
        --download)
            DOWNLOAD=1
            NO_BUILD=1
            shift
            ;;
        --no-build)
            NO_BUILD=1
            shift
            ;;
        --interactive)
            ACTION=configure
            shift
            ;;
        --bashrc-only)
            ACTION=bashrc_only
            shift
            ;;
        --status)
            ACTION=status
            shift
            ;;
        --uninstall-bashrc)
            ACTION=uninstall
            shift
            ;;
        *)
            printf 'unknown option: %s\n' "$1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

case $PROFILE in
    comfort | highlight | prompt) ;;
    *)
        printf 'unknown profile: %s\n' "$PROFILE" >&2
        exit 2
        ;;
esac

case $ACTION in
    status)
        print_status
        exit 0
        ;;
    uninstall)
        uninstall_bashrc
        printf 'Removed the managed MBX block from %s/.bashrc\n' "$HOME"
        exit 0
        ;;
    bashrc_only)
        write_bashrc
        printf 'Updated %s/.bashrc with a managed MBX block\n' "$HOME"
        exit 0
        ;;
    configure)
        if ((NO_BUILD == 0)); then
            install_build_or_download
        fi
        extra=(--no-build)
        ((WRITE_BASHRC == 1)) && extra+=(--bashrc)
        ((PROFILE_SET == 1)) && extra+=(--preset "$PROFILE")
        exec bash "$ROOT/scripts/configure.bash" "${extra[@]}"
        ;;
esac

# `--download` sets NO_BUILD to suppress the default cargo build, but the
# download itself must still run; a failed download falls back to cargo
# unless --no-build was also given, in which case install fails loudly.
if ((NO_BUILD == 0 || DOWNLOAD == 1)); then
    install_build_or_download
fi

write_profile "$(config_path)"
printf 'Wrote %s (profile %s)\n' "$(config_path)" "$PROFILE"

if ((WRITE_BASHRC == 1)); then
    write_bashrc
    printf 'Updated %s/.bashrc with a managed MBX block\n' "$HOME"
else
    printf 'Did not edit ~/.bashrc. For this shell:\n\n  source %q\n\n' \
        "$ROOT/bash/init.bash"
    printf 'Persist with: bash %q --profile %s --bashrc --no-build\n' \
        "$ROOT/scripts/install.bash" "$PROFILE"
fi

print_cheatsheet
